### PR TITLE
Fix ImplicitQualifiedImport and UnusedExplicitImport

### PR DESCRIPTION
**Pull request by ljrk0**
This fixes a bunch of warnings when run with purs 0.15.12

### CODE REVIEW

**Comment by thought2** [comment]
Thanks for the contribution, however I think the problem of seeing library warnings should be handled at a different level.
Do you already use the new spago? It has a nice psa integration, you can add this in the `spago.yaml` of your project:

```
workspace:
  build_opts:
    censor_library_warnings: all 
```

Better clean `.spago` folder to see the effect. This should silent all warnings produced by libraries.

Apart from that, On the side of this library:
In this case it was a conscious decision to allow `ImplicitQualifiedImport` warnings. I think it just adds unnecessary boilerplate in such re-export modules. Now I whitelisted it in the `spago.yaml`, See: https://github.com/thought2/purescript-ts-bridge/commit/372f1871d44c8ad50f42c01c830ff241c19ff1aa

**Comment by ljrk0** [comment]
Ah, I'm completely new to the whole PureScript world and currently just evaluating whether it makes sense for us (basically, I need to call two different TypeScript APIs, either I write most of the interfacing code in TypeScript and build helpers in PureScript, or I go all-in and create bindings for all the TS functions).

Anyway, this option makes a lot of sense and I'll definitely look into it, reminds me a bit of GCC/LLVM's `-isystem` (instead of `-I`) option to include headers of libraries as "system" and not report warnings for those.  Thanks!

**Comment by thought2** [comment]
@ljrk0 
Ok, sounds interesting. Actually I never really documented how this library can be used for FFI. I focused more on documenting the other way around (call PureScript code from TypeScript) which I guess is even less common.

So I took this as motivation to write a blog post about it:

https://thought2.github.io/blog/purescript-ffi/

In this process I also brought back `ts-bridge` to the latest package set. I replaced some dependencies and added temporary workarounds for others.

Let me know if you have any issues with the library.

**Comment by ljrk0** [comment]
Wow, that's an amazing blog post and gave me some real insights in how to use this library the other way around!  Indeed, thats probably a lot more common, and also much more what I had in mind initially.

However, I did try myself on the on the other way around (r/n w/o ts-bridge), by writing a few helpful functions in PureScript to expose them to TypeScript, such as an equivalent to Haskell's `partitionWith` (probably quite unidiomatic):


```purescript
partitionWith :: forall a b c. (a -> Either b c) -> Array a -> Tuple (Array b) (Array c)
partitionWith f xs' = case uncons xs' of
  Just { head: x, tail: xs } -> case (f x) of
    Left b -> Tuple (b:bs) cs
    Right c -> Tuple bs (c:cs)
    where
      Tuple bs cs = partitionWith f xs
  Nothing -> Tuple [] []
```

In order to expose that to Js/Ts, I followed [FFI Tips](https://github.com/purescript/documentation/blob/master/guides/FFI-Tips.md) and created a wrapper function which a) uncurries the applied function as well as b) adds two additional arguments to pass the `Left` and `Right` constructors and c) converts the returned `Tuple` into a `TupleRecord a b`, since Js doesn't have proper tuples but only Array's of mixed types:

```purescript
type TupleRecord a b = {
  fst :: a,
  snd :: b 
}

tsPartitionWith :: forall a b c. (Fn3 (b -> Either b c) (c -> Either b c) a (Either b c)) -> Array a -> TupleRecord (Array b) (Array c)
tsPartitionWith f a = { fst: x, snd: y }
  where
    Tuple x y = partitionWith (runFn3 f Left Right) a
```

I can now call this from JavaScript:

```javascript
var f = tsPartitionWith(
  (left,right,arg) => (arg < 3) ? left("too small") : right(arg+3)
);
var tuple = f([1,2,0,5,3,2,5,100,-1])
console.log(tuple.fst)
console.log(tuple.snd)
```

which does indeed give me:

```javascript
[ 'too small', 'too small', 'too small', 'too small', 'too small' ]
[ 8, 6, 8, 103 ]
```

In that case, however, it's probably much easier to just use https://gcanti.github.io/fp-ts/

Anyway, thank you *a lot* for the insights!

**Comment by thought2** [comment]
That's an interesting example. I actually got into ts-bridge when I was working on a web app in which the frontend views were written in React/TypeScript and the state management was written in PureScript.

I think there are generally two approaches to exposing PureScript functions to TypeScript:
1. Direct Mapping: Expose the functions as they are. Types that don't exist in TypeScript get exposed as opaque types and constructors and destructors are provided to to deal with them.
2. TS idiomatic Mapping: Expose the functions in a wrapper which uses only types which exist in TypeScript

I think your approach is a mix of both. The PureScript `Tuple` is replaced by a record and contructors are provided (in place) for creating `Either` values.

I cannot really recommend the one or the other, I think it depends mainly on how many PureScript specifics you want/need to hide on the TypeScript side. 

I give you some examples for both approaches and how to use ts-bridge for it.

Btw: Feel free to skip the following, I write this down for a great part because I need to clear my mind about
the current state of this library, how to proceed with it and how to find "best practices" which can be communicated easily to others.


## 1. Approach: Direct Mapping

One could expose `partitionWith` as it is:

```hs
partitionWith :: forall a b c. (a -> Either b c) -> Array a -> Tuple (Array b) (Array c)
partitionWith f xs' = (... your code)
```

If you try to use this with ts-bridge you'll get a compile error. ts-bridge recursively goes through the type signature and stringifies each type if there is a type class instance for it. This is true for all types used in here, but it cannot find an instance for the type variables because there's nothing like "default instances" in PureScript.
So for a moment let's give it a signature with only concrete types. This works right away with `ts-bridge`.

```hs
partitionWithTs :: (String -> Either Number Boolean) -> Array String -> Tuple (Array Number) (Array Boolean)
partitionWithTs = partitionWith

tsModules :: Either TSB.AppError (Array DTS.TsModuleFile)
tsModules =
  TSB.tsModuleFile "Try"
    [ TSB.tsValues TSB.Tok
        { partitionWithTs
        }
    ]
```

`ts-bridge` will generate those three files:

```
output/Data.Either/index.d.ts
output/Data.Tuple/index.d.ts
output/Try/index.d.ts
```

With the following contents (after applying `prettier` to it):

`output/Data.Either/index.d.ts`:
```
export type Either<A, B> = {
  readonly __brand: unique symbol;
  readonly __arg1: A;
  readonly __arg2: B;
};
```

`output/Data.Tuple/index.d.ts`:
```
export type Tuple<A, B> = {
  readonly __brand: unique symbol;
  readonly __arg1: A;
  readonly __arg2: B;
};
```

`output/Try/index.d.ts`:
```
export const partitionWithTs: (
  _: (_: string) => import("../Data.Either").Either<number, boolean>
) => (
  _: Array<string>
) => import("../Data.Tuple").Tuple<Array<number>, Array<boolean>>;
```



Which is maybe a bit surprising. Even though only one value was exposed, 3 modules where generated.
PureScript has nominal types, that means every type has a unique place where it is defined.
Once you use a nominal type, e.g. `Either` it generates a module for it or adds it to that module if it already exists.
Nominal types are generated as branded types in TypeScript, which means they are just a record with a unique symbol.
The trick is, that you cannot create values of this type directly, this simulates its opaque nature.

So at this point the generated code is pretty useless from a TypeScript perspective.

we have to expose constructors and destructors for the branded/nominal/opaque types we want to use in TypeScript.

For `Either` this would be:


```hs
mkEither :: forall a b. { mkLeft :: a -> Either a b, mkRight :: b -> Either a b }
mkEither =
  { mkLeft: Left
  , mkRight: Right
  }

matchEither :: forall a b z. { onLeft :: a -> z, onRight :: b -> z } -> Either a b -> z
matchEither rec val = case val of
  Left l -> rec.onLeft l
  Right r -> rec.onRight r
```

I apply the same pattern for `Tuple`, even though it's a bit silly for a type with a single constructor:


```hs
mkTuple :: forall a b. { mkTuple :: a -> b -> Tuple a b }
mkTuple = { mkTuple: Tuple }

matchTuple :: forall a b z. { onTuple :: a -> b -> z } -> Tuple a b -> z
matchTuple rec val = case val of
  Tuple t1 t2 -> rec.onTuple t1 t2
```


Now we need to expose all those helpers to TypeScript. But unfortunately there are many type variables in the signatures.
The trick is to use dummy types for them, which generate type variables on the TypeScript side.

For convenience I define some type aliases for the type variables:


```hs
type A = TSB.TypeVar "A"
type B = TSB.TypeVar "B"
type C = TSB.TypeVar "C"
type Z = TSB.TypeVar "Z"
```


For the `partitionWith` function we can now write the type variables `A`, `B` and `C`
instead of the concrete types:



```hs
partitionWithTs2 :: (A -> Either B C) -> Array A -> Tuple (Array B) (Array C)
partitionWithTs2 = partitionWith
```

This would work for the other values as well but it's a bit tedious to define a second top level value for each of them.
It's enough to add the type signatures right before they get exported with ts-bridge:



```hs
tsModules2 :: Either TSB.AppError (Array DTS.TsModuleFile)
tsModules2 =
  TSB.tsModuleFile "Try"
    [ TSB.tsValues TSB.Tok
        ( { partitionWith
          , mkEither
          , matchEither
          , mkTuple
          , matchTuple
          }
            :: { partitionWith :: (A -> Either B C) -> Array A -> Tuple (Array B) (Array C)
               , mkEither :: { mkLeft :: A -> Either A B, mkRight :: B -> Either A B }
               , matchEither :: { onLeft :: A -> Z, onRight :: B -> Z } -> Either A B -> Z
               , mkTuple :: { mkTuple :: A -> B -> Tuple A B }
               , matchTuple :: { onTuple :: A -> B -> Z } -> Tuple A B -> Z
               }
        )
    ]
```

This is a bit repetitive, and there are several shorter ways to express the same in a shorter way.
E.g by. using Visible Type Applications or Wildcards in the types.
I am not yet sure what's the best way to do it, so I keep it in the most explicit form for now.

If you run `ts-bridge` CLI with the new exports, you'll still get the same files generated,
with a different content only in the `Try` module itself:

```ts
export const matchEither: <A, Z, B>(_: {
  readonly onLeft: (_: A) => Z;
  readonly onRight: (_: B) => Z;
}) => (_: import("../Data.Either").Either<A, B>) => Z;

export const matchTuple: <A, B, Z>(_: {
  readonly onTuple: (_: A) => (_: B) => Z;
}) => (_: import("../Data.Tuple").Tuple<A, B>) => Z;

export const mkEither: {
  readonly mkLeft: <A, B>(_: A) => import("../Data.Either").Either<A, B>;
  readonly mkRight: <A, B>(_: B) => import("../Data.Either").Either<A, B>;
};

export const mkTuple: {
  readonly mkTuple: <A>(
    _: A
  ) => <B>(_: B) => import("../Data.Tuple").Tuple<A, B>;
};

export const partitionWith: <A, B, C>(
  _: (_: A) => import("../Data.Either").Either<B, C>
) => (_: Array<A>) => import("../Data.Tuple").Tuple<Array<B>, Array<C>>;
```

And voilà, we have a TypeScript API for our PureScript functions. We can use it like this:

```ts
import * as Try from "../output/Try/index.js";

const main = () => {
  const f = Try.partitionWith<number, string, number>((arg) =>
    arg < 3 ? Try.mkEither.mkLeft("too small") : Try.mkEither.mkRight(arg + 3)
  );

  const result = f([1, 2, 0, 5, 3, 2, 5, 100, -1]);

  const result2 = Try.matchTuple<
    string[],
    number[],
    { lefts: string[]; rights: number[] }
  >({ onTuple: (lefts) => (rights) => ({ lefts, rights }) })(result);

  console.log(result2.lefts);
  console.log(result2.rights);
};

main();
```

As you can see, sometimes you need to help the TS compiler a bit with the type arguments (`<number, string, number>`).
This is not unsafe, because you can only provide "the right types". Typescript is not capable of inferring the types here.
If you use the `pipe` function from `fp-ts`, the annotations can be avoided in many places.

I think this is the most powerful way to expose PureScript functions to TypeScript, mainly because it works both ways.
But it comes with a cost. One needs a good understanding of how the mapping works
and I think consuming this API works best for people who are familiar with PureScript.


## 2. Approach: TS idiomatic Mapping

If you want to make the TS API as idiomatic as possible, you can use the following approach:

Tuples are converted to records as you did it and the data type is converted to a variant type.
The advantage of variant types is that they have a known (and simple) representation in TypeScript.



```hs
partitionWithTsIdiomatic
  :: forall a b c
   . (a -> Variant (left :: b, right :: c))
  -> Array a
  -> { lefts :: Array b, rights :: Array c }
partitionWithTsIdiomatic f xs =
  let
    variantToEither = case_ # onMatch
      { left: Left
      , right: Right
      }
    Tuple lefts rights = partitionWith (f >>> variantToEither) xs
  in
    { lefts, rights }
```

Export looks like this:


```hs
tsModules3 :: Either TSB.AppError (Array DTS.TsModuleFile)
tsModules3 =
  TSB.tsModuleFile "Try"
    [ TSB.tsValues TSB.Tok
        ( { partitionWithTsIdiomatic
          }
            :: { partitionWithTsIdiomatic ::
                   (A -> Variant (left :: B, right :: C))
                   -> Array A
                   -> { lefts :: Array B, rights :: Array C }
               }
        )
    ]
```


Creates only one single TS file:
```ts
export const partitionWithTsIdiomatic: <A, B, C>(
  _: (
    _: A
  ) =>
    | { readonly type: "left"; readonly value: B }
    | { readonly type: "right"; readonly value: C }
) => (_: Array<A>) => { readonly lefts: Array<B>; readonly rights: Array<C> };
```

Usage:

```ts
import * as Try from "../output/Try/index.js";

const main = () => {
  const f = Try.partitionWithTsIdiomatic<number, string, number>((arg) =>
    arg < 3
      ? { type: "left", value: "too small" }
      : { type: "right", value: arg + 3 }
  );

  const result = f([1, 2, 0, 5, 3, 2, 5, 100, -1]);

  console.log(result.lefts);
  console.log(result.rights);
};

main();
```

This is way simpler to use on the TypeScript side. And actually in this case it's simple on the PureScript side.
But once the functions become more complex,
more callbacks etc. it becomes more and more boilerplate and maintenance work on the PureScript side.

**Pull request closed without merging**
